# Generated by Django 5.0a1 on 2025-12-25 04:15

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staffinfo_created_at_studentinfo_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in_time'], 'verbose_name': 'Điểm danh', 'verbose_name_plural': 'Điểm danh'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bài viết blog', 'verbose_name_plural': 'Bài viết blog'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Lớp học', 'verbose_name_plural': 'Lớp học'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Vai trò', 'verbose_name_plural': 'Vai trò'},
        ),
        migrations.AlterModelOptions(
            name='staffinfo',
            options={'verbose_name': 'Thông tin giáo viên', 'verbose_name_plural': 'Thông tin giáo viên'},
        ),
        migrations.AlterModelOptions(
            name='staffrole',
            options={'verbose_name': 'Vai trò giáo viên', 'verbose_name_plural': 'Vai trò giáo viên'},
        ),
        migrations.AlterModelOptions(
            name='studentclassdetails',
            options={'verbose_name': 'Chi tiết lớp học', 'verbose_name_plural': 'Chi tiết lớp học'},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name': 'Thông tin sinh viên', 'verbose_name_plural': 'Thông tin sinh viên'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.IntegerField(verbose_name='Trạng thái điểm danh'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(verbose_name='Thời gian vào'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id_attendance',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Mã điểm danh'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id_classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentinfo', verbose_name='Sinh viên'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('SV', 'Sinh viên'), ('GV', 'Giảng viên'), ('ALL', 'Tất cả')], default='ALL', max_length=15, verbose_name='Loại bài viết'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='begin_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='begin_time',
            field=models.TimeField(verbose_name='Giờ bắt đầu'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='day_of_week_begin',
            field=models.IntegerField(verbose_name='Ngày trong tuần bắt đầu'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(verbose_name='Giờ kết thúc'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id_classroom',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Mã lớp'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staffinfo', verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.TextField(verbose_name='Tên lớp'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(through='main.StudentClassDetails', to='main.studentinfo', verbose_name='Sinh viên'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tên vai trò'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='birthday',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo tài khoản'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='email',
            field=models.TextField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='id_staff',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã giáo viên'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='password',
            field=models.TextField(verbose_name='Mật khẩu'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='phone',
            field=models.TextField(verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='roles',
            field=models.ManyToManyField(related_name='staff_role', through='main.StaffRole', to='main.role', verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='staff_name',
            field=models.TextField(verbose_name='Tên giáo viên'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role', verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staffinfo', verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='studentclassdetails',
            name='id_classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classroom', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='studentclassdetails',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentinfo', verbose_name='Sinh viên'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='PathImageFolder',
            field=models.TextField(verbose_name='Đường dẫn thư mục ảnh'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='birthday',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo tài khoản'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.TextField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='id_student',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã sinh viên'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='password',
            field=models.TextField(verbose_name='Mật khẩu'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='phone',
            field=models.TextField(verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student_name',
            field=models.TextField(verbose_name='Tên sinh viên'),
        ),
        migrations.AlterUniqueTogether(
            name='staffrole',
            unique_together={('staff', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='studentclassdetails',
            unique_together={('id_classroom', 'id_student')},
        ),
    ]
